[package]
name = "asa-migrations"
version.workspace = true
edition.workspace = true

[[bin]]
name = "migrations"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
sqlx.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
